name: poke_dex
description: Uma pokedex para analisar seus pokemonzinhos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  custom_pokemons:
    path: 'modules/custom_pokemons'
  original_pokemons:
    path: 'modules/original_pokemons'
  home_pokemons:
    path: 'modules/home_pokemons'
  commons_dependencies:
    path: 'modules/commons_dependencies'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
