include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]

linter:
  rules:
    prefer_relative_imports: true
    directives_ordering: true
    sort_constructors_first: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true